---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Dou.
--- DateTime: 2023/12/2 12:57
---
---comments
---@param input string
---@param patterns table
---@return number|nil
---@return number|nil
---@return number|nil
function string.multi_find(input, patterns)
  local seps = pairs(patterns)
  local _start, _end, result, _index
  for _, sep in seps do
    local s, e = input:find(sep)
    if s ~= nil and (_start == nil or s < result) then
      _start, _end = s, e
    end
  end
  return _start, _end, _index
end

---comments
---@param input string
---@param seps string
---@return table
function string.split(input, seps)
  local result = {}
  while true do
    local _s, _e = input:find(seps)
    if _s and _e then
      table.insert(result, input:sub(1, _s - 1))
      input = input:sub(_e + 1, -1)
    else
      table.insert(result, input)
      break
    end
  end
  return result
end

function string.find_indicies(s, patterns)
  local result = {}
  if type(patterns) == "string" then
    patterns = { patterns }
  end
  for index, pattern in pairs(patterns) do
    local _start, _end = 0, 0
    while true do
      _start, _end = s:find(pattern, _end + 1)
      if _start == nil or _end == nil then
        break
      else
        table.insert(result, { _start, _end, index })
      end
    end
  end
  table.sort(result, function(a, b) return a[1] < b[1] end)
  return result
end
